### PR TITLE
include argument to start with narr_cell instead of lat/lon. closes #25

### LINKED ISSUE #25: argument to start with narr cell number instead of coordinates

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by cole-brokamp** [comment]
Looks like sf is failing to install because its missing gdal dependency on the CI machine?

https://github.com/geomarker-io/addNarrData/pull/26/checks?check_run_id=3009465289#step:4:485

This is causing a failed install for dht because sf is a dependency.

**Comment by erikarasnick** [comment]
I had included sf because dht has functionality to read in csv and transform all at once. Wondering if I should remove that so that sf isn't a dependency every time we use dht.

**Comment by cole-brokamp** [comment]
Maybe we can make it a suggested dependency?  

We can do something like this: https://github.com/r-spatial/sf/blob/c99226b29ccd79efc20164794a8a10f3d06606f7/R/tidyverse.R#L438-L439

To alert the user that the sf package is required for that specific function only after it is called and when sf is not already available?

**Comment by erikarasnick** [comment]
So I wasn't thinking that this package still needs sf to assign the narr cell numbers...

**Comment by cole-brokamp** [comment]
let's expand the check to use windows, macOS, and linux.  as long as at least two of these work, then we will be okay to merge.  the sf availability definitely seems to be something on the CI runners...

**Comment by erikarasnick** [comment]
only fails on the mac CI. I will merge 👍🏼

**Review by cole-brokamp — APPROVED** [review]

**Pull request merged**
